// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuYAr3B9ttK9Q6AJDtFqU0YoRQdrSFZUY',
    appId: '1:114659896723:android:a0d1c93a190ce77c480c66',
    messagingSenderId: '114659896723',
    projectId: 'plantecommerce-b7dd8',
    storageBucket: 'plantecommerce-b7dd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC7W1z5qUhuhzlt68DHldGzWlM8dFpGg0',
    appId: '1:114659896723:ios:db95ba82e4d329cb480c66',
    messagingSenderId: '114659896723',
    projectId: 'plantecommerce-b7dd8',
    storageBucket: 'plantecommerce-b7dd8.appspot.com',
    androidClientId: '114659896723-lmbtnrr7veqc9147ckl76pjjdp67iqcn.apps.googleusercontent.com',
    iosClientId: '114659896723-ttlvi7ighe0trcb78mk4kkc3a9cmd6c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.plantApp',
  );

}